[backdrop]
enabled = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 600.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 900.0

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 660.0

[keybinds]
down = [ "Down", "Ctrl+n" ]
up = [ "Up", "Ctrl+p" ]
validate = [ "Return", "KP_Enter", "space", "Ctrl+y" ]

[osd]
position = "bottom_center"

[shell]
font_family = "Iosevka NF"
password_style = "random"

[shell.animation]
speed = 1.5000000223517418

[shell.panel]
transparency_mode = "soft"

[theme]
builtin = "Kanagawa"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
enabled = true
directory = "/home/kaezr/Pictures/wallpapers"

[wallpaper.default]
path = "/home/kaezr/Pictures/wallpapers/pokemon.png"
